---
- name: Create variable from command
  command: "date +%Y%m%d-%H%M"
  register: timestamp

- name: Create backup directory
  file:
    path: /home/juniorBackup/Broadlearning_{{timestamp.stdout}}
    state: directory

- name: Create tar.gz archive backup
  archive:
     path:
        - "{{home_dir}}/junior20"
     dest: /home/juniorBackup/Broadlearning_{{timestamp.stdout}}/backup.tar.gz
     format: gz
     force_archive: true
